/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppOpsBrainRouteImport } from './routes/app.ops-brain'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppFlowsRouteImport } from './routes/app.flows'
import { Route as AppFailuresRouteImport } from './routes/app.failures'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminScenariosRouteImport } from './routes/admin.scenarios'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin.feature-flags'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AppTransactionIdRouteImport } from './routes/app.transaction.$id'
import { Route as AppIntegrationsIdRouteImport } from './routes/app.integrations.$id'
import { Route as AppIncidentIdRouteImport } from './routes/app.incident.$id'
import { Route as AppFlowsIdRouteImport } from './routes/app.flows.$id'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsBrainRoute = AppOpsBrainRouteImport.update({
  id: '/ops-brain',
  path: '/ops-brain',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppFailuresRoute = AppFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScenariosRoute = AdminScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AppTransactionIdRoute = AppTransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIdRoute = AppIntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIncidentIdRoute = AppIncidentIdRouteImport.update({
  id: '/incident/$id',
  path: '/incident/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIdRoute = AppFlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/flows': typeof AppFlowsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/ops-brain': typeof AppOpsBrainRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/flows/$id': typeof AppFlowsIdRoute
  '/app/incident/$id': typeof AppIncidentIdRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/flows': typeof AppFlowsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/ops-brain': typeof AppOpsBrainRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/flows/$id': typeof AppFlowsIdRoute
  '/app/incident/$id': typeof AppIncidentIdRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/flows': typeof AppFlowsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/ops-brain': typeof AppOpsBrainRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/flows/$id': typeof AppFlowsIdRoute
  '/app/incident/$id': typeof AppIncidentIdRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin/audit-logs'
    | '/admin/feature-flags'
    | '/admin/incidents'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/overview'
    | '/admin/providers'
    | '/admin/scenarios'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/app/api-keys'
    | '/app/assistant'
    | '/app/failures'
    | '/app/flows'
    | '/app/integrations'
    | '/app/ops-brain'
    | '/app/overview'
    | '/app/providers'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/transactions'
    | '/app/webhooks'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/app/flows/$id'
    | '/app/incident/$id'
    | '/app/integrations/$id'
    | '/app/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin/audit-logs'
    | '/admin/feature-flags'
    | '/admin/incidents'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/overview'
    | '/admin/providers'
    | '/admin/scenarios'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/app/api-keys'
    | '/app/assistant'
    | '/app/failures'
    | '/app/flows'
    | '/app/integrations'
    | '/app/ops-brain'
    | '/app/overview'
    | '/app/providers'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/transactions'
    | '/app/webhooks'
    | '/admin'
    | '/app'
    | '/admin/tenants/$id'
    | '/app/flows/$id'
    | '/app/incident/$id'
    | '/app/integrations/$id'
    | '/app/transaction/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin/audit-logs'
    | '/admin/feature-flags'
    | '/admin/incidents'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/overview'
    | '/admin/providers'
    | '/admin/scenarios'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/app/api-keys'
    | '/app/assistant'
    | '/app/failures'
    | '/app/flows'
    | '/app/integrations'
    | '/app/ops-brain'
    | '/app/overview'
    | '/app/providers'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/transactions'
    | '/app/webhooks'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/app/flows/$id'
    | '/app/incident/$id'
    | '/app/integrations/$id'
    | '/app/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ops-brain': {
      id: '/app/ops-brain'
      path: '/ops-brain'
      fullPath: '/app/ops-brain'
      preLoaderRoute: typeof AppOpsBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows': {
      id: '/app/flows'
      path: '/flows'
      fullPath: '/app/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/failures': {
      id: '/app/failures'
      path: '/failures'
      fullPath: '/app/failures'
      preLoaderRoute: typeof AppFailuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scenarios': {
      id: '/admin/scenarios'
      path: '/scenarios'
      fullPath: '/admin/scenarios'
      preLoaderRoute: typeof AdminScenariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/transaction/$id': {
      id: '/app/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/app/transaction/$id'
      preLoaderRoute: typeof AppTransactionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations/$id': {
      id: '/app/integrations/$id'
      path: '/$id'
      fullPath: '/app/integrations/$id'
      preLoaderRoute: typeof AppIntegrationsIdRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/app/incident/$id': {
      id: '/app/incident/$id'
      path: '/incident/$id'
      fullPath: '/app/incident/$id'
      preLoaderRoute: typeof AppIncidentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/$id': {
      id: '/app/flows/$id'
      path: '/$id'
      fullPath: '/app/flows/$id'
      preLoaderRoute: typeof AppFlowsIdRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminScenariosRoute: typeof AdminScenariosRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminScenariosRoute: AdminScenariosRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppFlowsRouteChildren {
  AppFlowsIdRoute: typeof AppFlowsIdRoute
}

const AppFlowsRouteChildren: AppFlowsRouteChildren = {
  AppFlowsIdRoute: AppFlowsIdRoute,
}

const AppFlowsRouteWithChildren = AppFlowsRoute._addFileChildren(
  AppFlowsRouteChildren,
)

interface AppIntegrationsRouteChildren {
  AppIntegrationsIdRoute: typeof AppIntegrationsIdRoute
}

const AppIntegrationsRouteChildren: AppIntegrationsRouteChildren = {
  AppIntegrationsIdRoute: AppIntegrationsIdRoute,
}

const AppIntegrationsRouteWithChildren = AppIntegrationsRoute._addFileChildren(
  AppIntegrationsRouteChildren,
)

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppFailuresRoute: typeof AppFailuresRoute
  AppFlowsRoute: typeof AppFlowsRouteWithChildren
  AppIntegrationsRoute: typeof AppIntegrationsRouteWithChildren
  AppOpsBrainRoute: typeof AppOpsBrainRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIncidentIdRoute: typeof AppIncidentIdRoute
  AppTransactionIdRoute: typeof AppTransactionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppFailuresRoute: AppFailuresRoute,
  AppFlowsRoute: AppFlowsRouteWithChildren,
  AppIntegrationsRoute: AppIntegrationsRouteWithChildren,
  AppOpsBrainRoute: AppOpsBrainRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppIncidentIdRoute: AppIncidentIdRoute,
  AppTransactionIdRoute: AppTransactionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
